// // import localFont from "next/font/local";
// import { Outfit, outfit } from 'next/font/google'
// import "./globals.css";

// const outfit = Outfit({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = Outfit({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "ABG Blog",
//   description: "Generated by ABG Blog",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// Import the Outfit font from Google
import { Outfit } from 'next/font/google';
import './globals.css';

// Initialize the Outfit font with a subset
const outfit = Outfit({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 
  variable: '--font-outfit',
  subsets: ['latin'], // Specify the subset
});

// Metadata for the page
export const metadata = {
  title: 'ABG Blog',
  description: 'Generated by ABG Blog',
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
